from pywikibot import Site, Page
from pywikibot.pagegenerators import PreloadingGenerator

extension_string = """3D
AJAXPoll
AbuseFilter
AdminLinks
AdvancedSearch
AntiSpoof
ApprovedRevs
Arrays
ArticleCreationWorkflow
ArticleFeedbackv5
ArticlePlaceholder
ArticleRatings
AuthorProtect
AutoCreateCategoryPages
AutoCreatePage
Babel
BetaFeatures
BlogPage
Bootstrap
BreadCrumbs2
CSS
Calendar
CampaignEvents
Capiunto
Cargo
CategoryExplorer
CategorySortHeaders
CategoryTests
CategoryTree
CentralAuth
CentralNotice
CharInsert
CheckUser
CirrusSearch
Cite
CiteThisPage
CleanChanges
CodeEditor
CodeMirror
CollapsibleVector
CommentStreams
Commentbox
Comments
CommonsMetadata
ConfirmEdit
ContactPage
ContributionScores
CookieWarning
CountDownClock
CreatePage
CreatePageUw
CreateRedirect
CreateWiki
CreatedPagesList
CustomSearchProfiles
CustomSubtitle
DPLForum
DarkMode
DataDump
DataMaps
DataTransfer
DeleteUserPages
Description2
Disambiguator
DiscordNotifications
DiscussionTools
DismissableSiteNotice
DisplayTitle
Drafts
DummyFandoomMainpageTags
DynamicPageList
DynamicPageList3
DynamicSidebar
Echo
EditCountNeue
EditSimilar
EditSubpages
Editcount
Elastica
EmbedSpotify
EmbedVideo
EventBus
EventLogging
EventStreamConfig
ExternalData
FlaggedRevs
FlexDiagrams
Flow
FontAwesome
ForcePreview
Gadgets
Genealogy
GeoCrumbs
GeoData
GeoGebra
GlobalBlocking
GlobalCssJs
GlobalNewFiles
GlobalPreferences
GlobalUsage
GlobalUserPage
GlobalWatchlist
GoogleDocs4MW
GoogleForms
GoogleNewsSitemap
GroupsSidebar
GuidedTour
HAWelcome
HeaderTabs
HideSection
HighlightLinksInCategory
IPInfo
ImageMap
ImageRating
ImportDump
IncidentReporting
InputBox
InterwikiDispatcher
InterwikiSorting
JSBreadCrumbs
JavascriptSlideshow
Josa
JsCalendar
JsonConfig
Kartographer
LabeledSectionTransclusion
LanguageSelector
LastModified
LdapAuthentication
Lingo
LinkCards
LinkSuggest
LinkTarget
LinkTitles
Linter
LockAuthor
LoginNotify
LogoFunctions
Loops
MachineTranslation
MagicNoCache
ManageWiki
Maps
MassEditRegex
MassMessage
Math
MatomoAnalytics
MediaSearch
MediaSpoiler
MediaWikiChat
Mermaid
MintyDocs
MirahezeMagic
MobileDetect
MobileFrontend
MobileTabsPlugin
Moderation
MsCalendar
MsCatSelect
MsLinks
MsUpload
MultiBoilerplate
MultiPurge
MultimediaViewer
MyVariables
NamespacePreload
NativeSvgHandler
NearbyPages
Network
NewSignupPage
NewUserMessage
NewUserNotif
NewestPages
Newsletter
NoTitle
Nuke
NukeDPL
NumberHeadings
OATHAuth
OAuth
OpenGraphMeta
OreDict
OrphanedTalkPages
PDFEmbed
PWA
PageAssessments
PageForms
PageImages
PageLanguage
PageNotice
PageProperties
PageSchemas
PageTriage
PagedTiffHandler
ParserFunctions
ParserMigration
PdfHandler
PerPageLanguage
Phonos
PipeEscape
Poem
PollNY
Popups
PortableInfobox
Preloader
ProofreadPage
PropertySuggester
ProtectSite
ProtectionIndicator
Purge
QuickInstantCommons
Quiz
QuizGame
RSS
RandomGameUnit
RandomImage
RandomImageByCategory
RandomSelection
RatePage
RealMe
RelatedArticles
RemovePII
RemoveRedlinks
ReplaceText
Report
ReportIncident
RequestSSL
RevisionSlider
RightFunctions
RobloxAPI
RottenLinks
SandboxLink
SaneCase
Score
Screenplay
Scribunto
SecureLinkFixer
SecurePoll
SemanticDrilldown
SemanticFormsSelect
SemanticMediaWiki
SemanticScribunto
Share
ShortDescription
SimpleBatchUpload
SimpleBlogPage
SimpleChanges
SimpleTooltip
SkinPerPage
SnapProjectEmbed
SocialProfile
SoftRedirector
SpamBlacklist
SpeciallyCursed
Spoilers
SpriteSheet
StandardDialogs
StopForumSpam
StructuredNavigation
SubPageList3
SubpageFun
SyntaxHighlight_GeSHi
TabberNeue
Tabs
TemplateData
TemplateSandbox
TemplateStyles
TemplateStylesExtender
TemplateWizard
TextExtracts
Thanks
Theme
ThemeToggle
Tilesheets
TimeMachine
TimedMediaHandler
Timeline
TimezoneConverter
TitleBlacklist
TitleIcon
TitleKey
TocTree
TorBlock
Translate
TranslationNotifications
TreeAndMenu
TwoColConflict
UniversalLanguageSelector
UnlinkedWikibase
UnusedRedirects
UploadWizard
UploadsLink
UrlGetParameters
UrlShortener
UserFunctions
UserPageEditProtection
UserProfileV2
VEForAll
Variables
VariablesLua
Video
VisualEditor
VoteNY
WebAuthN
WebChat
WikiCategoryTagCloud
WikiDiscover
WikiEditor
WikiForum
WikiLove
WikiSEO
WikiTextLoggedInOut
Wikibase
WikibaseCirrusSearch
WikibaseEdtf
WikibaseLexeme
WikibaseLexemeCirrusSearch
WikibaseLocalMedia
WikibaseMediaInfo
WikibaseQualityConstraints
WikidataPageBanner
WikimediaIncubator
YouTube
CLDR
ScratchBlocks
Snapblocks
WikiHiero"""

wmf_extension_string = """3D
AbuseFilter
AdvancedSearch
AntiSpoof
ApiFeatureUsage
ArticleCreationWorkflow
ArticlePlaceholder
AutoModerator
Babel
BetaFeatures
BounceHandler
Calendar-Wikivoyage
CampaignEvents
Campaigns
Capiunto
CategoryTree
CentralAuth
CentralNotice
CharInsert
Chart
CheckUser
CirrusSearch
Cite
CiteThisPage
Citoid
CLDR
CodeEditor
CodeMirror
CodeMirror/5
Cognate
Collection
CommonsMetadata
CommunityConfiguration
CommunityRequests
ConfirmEdit
ContactPage
ContentTranslation
CreditsSource
Dashiki
Disambiguator
DiscussionTools
DismissableSiteNotice
DonationInterface
DynamicPageList
E
EasyTimeline
Echo
Elastica
ElectronPdfService
EmailAuth
EntitySchema
EventBus
EventLogging
EventStreamConfig
ExtensionDistributor
ExternalGuidance
FeaturedFeeds
FileExporter
FileImporter
FlaggedRevs
FundraiserLandingPage
FundraisingEmailUnsubscribe
FundraisingTranslateWorkflow
Gadgets
GeoCrumbs
GeoData
GlobalBlocking
GlobalCssJs
GlobalPreferences
GlobalUsage
GlobalUserPage
GlobalWatchlist
GoogleNewsSitemap
GrowthExperiments
GuidedTour
ImageMap
ImageSuggestions
InputBox
Insider
Interwiki
InterwikiSorting
IPInfo
IPReputation
Josa
JsonConfig
Kartographer
Labeled Section Transclusion
LandingCheck
Linter
LiquidThreads
LoginNotify
MapSources
MassMessage
Math
MediaModeration
MediaSearch
MetricsPlatform
MobileApp
MobileFrontend
MultimediaViewer
NavigationTiming
NearbyPages
NetworkSession
Newsletter
NewUserMessage
Nuke
OATHAuth
OAuth
OAuthRateLimiter
ORES
PageAssessments
PagedTiffHandler
PageImages
PageNotice
PageTriage
PageViewInfo
Paragraph-based Edit Conflict Interface
ParserFunctions
ParserMigration
Parsoid
PdfHandler
Phonos
Poem
Popups
Proofread Page
PropertySuggester
QuickSurveys
Quiz
ReadingLists
RealMe
RelatedArticles
ReportIncident
RevisionSlider
RSS
SandboxLink
Score
Scribunto
SearchExtraNS
SearchVue
SecureLinkFixer
SecurePoll
ShortUrl
SiteMatrix
SpamBlacklist
StopForumSpam
StructuredDiscussions
SubPageList3
SubpageSortkey
SyntaxHighlight
TemplateData
TemplateSandbox
TemplateStyles
TemplateWizard
TextExtracts
Thanks
TheWikipediaLibrary
TimedMediaHandler
TitleBlacklist
TocTree
TorBlock
Translate
TranslationNotifications
TrustedXFF
UniversalLanguageSelector
UploadsLink
UploadWizard
UrlShortener
VisualEditor
WebAuthn
Wikibase
Wikibase Client
Wikibase Repository
WikibaseCirrusSearch
WikibaseLexeme
WikibaseLexemeCirrusSearch
WikibaseMediaInfo
WikibaseQualityConstraints
Wikidata.org
WikidataPageBanner
WikiEditor
WikiHiero
WikiLambda
WikiLove
WikimediaApiPortalOAuth
WikimediaBadges
WikimediaCampaignEvents
WikimediaEditorTasks
WikimediaEvents
WikimediaIncubator
WikimediaMaintenance
WikimediaMessages
Wikisource
Wikistories
XAnalytics"""

def get_wmf_extensions() -> set[str]:
    return set(e.replace(' ', '').lower() for e in wmf_extension_string.splitlines())

def main():
    s = Site('beta')
    s.login()
    extensions: list[str] = extension_string.splitlines()
    wmf_extensions: set[str] = get_wmf_extensions()
    for page in PreloadingGenerator(Page(s, e) for e in extensions):
        setattr(page, "_bot_may_edit", True)
        edited = False
        if not page.exists():
            page.text = "{{ManualTest}}"
            edited = True
        if "{{WMF}}" not in page.text and page.title().replace(' ', '').lower() in wmf_extensions:
            page.text = "{{WMF}}" + page.text
            edited = True
        if edited:
            page.save(summary="batch create pages")

if __name__ == '__main__':
    main()
