[project]
name = "miraheze"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bs4>=0.0.2",
    "lxml>=5.4.0",
    "pywikibot>=10.0.0",
    "requests>=2.32.3",
]

[tool.uv]
cache-dir = "D:\\uv\\cache"
